from __future__ import annotations

from enum import StrEnum


class CriterionState(StrEnum):
    PRESENT_CURRENT = "PRESENT_CURRENT"
    ABSENT_EXPLICIT = "ABSENT_EXPLICIT"
    HISTORICAL = "HISTORICAL"
    FAMILY_HISTORY_OR_OTHER_EXPERIENCER = "FAMILY_HISTORY_OR_OTHER_EXPERIENCER"
    UNCERTAIN = "UNCERTAIN"
    CONFLICTING = "CONFLICTING"
    NOT_DOCUMENTED = "NOT_DOCUMENTED"
    POST_CUTOFF_ONLY = "POST_CUTOFF_ONLY"
    MODEL_ABSTENTION = "MODEL_ABSTENTION"
    PARSE_FAILURE = "PARSE_FAILURE"
    INFERENCE_FAILURE = "INFERENCE_FAILURE"


UNRESOLVED_STATES = frozenset(
    {
        CriterionState.UNCERTAIN,
        CriterionState.CONFLICTING,
        CriterionState.NOT_DOCUMENTED,
        CriterionState.POST_CUTOFF_ONLY,
        CriterionState.MODEL_ABSTENTION,
        CriterionState.PARSE_FAILURE,
        CriterionState.INFERENCE_FAILURE,
    }
)

FAILURE_STATES = frozenset(
    {CriterionState.PARSE_FAILURE, CriterionState.INFERENCE_FAILURE}
)


class AnchorEligibility(StrEnum):
    DIRECT_STRUCTURED = "DIRECT_STRUCTURED"
    STRUCTURED_ANCHOR_ELIGIBLE = "STRUCTURED_ANCHOR_ELIGIBLE"
    NOTE_ONLY_SEMANTIC = "NOTE_ONLY_SEMANTIC"
    DERIVED_DETERMINISTIC = "DERIVED_DETERMINISTIC"
    UNSUPPORTED_IN_EHR = "UNSUPPORTED_IN_EHR"


class MergeOutcome(StrEnum):
    AGREE_PRESENT = "AGREE_PRESENT"
    AGREE_ABSENT = "AGREE_ABSENT"
    STRUCTURED_ONLY = "STRUCTURED_ONLY"
    NOTE_ONLY = "NOTE_ONLY"
    CONFLICTING = "CONFLICTING"
    NOT_DOCUMENTED = "NOT_DOCUMENTED"
    POST_CUTOFF_ONLY = "POST_CUTOFF_ONLY"
    MODEL_ABSTENTION = "MODEL_ABSTENTION"
    SYSTEM_FAILURE = "SYSTEM_FAILURE"


class FailureCategory(StrEnum):
    COHORT_SELECTION_FAILURE = "COHORT_SELECTION_FAILURE"
    TEMPORAL_ALIGNMENT_FAILURE = "TEMPORAL_ALIGNMENT_FAILURE"
    STRUCTURED_MAPPING_FAILURE = "STRUCTURED_MAPPING_FAILURE"
    NOTE_RETRIEVAL_FAILURE = "NOTE_RETRIEVAL_FAILURE"
    SEMANTIC_GROUNDING_ERROR = "SEMANTIC_GROUNDING_ERROR"
    MODEL_ABSTENTION = "MODEL_ABSTENTION"
    MODEL_SCHEMA_FAILURE = "MODEL_SCHEMA_FAILURE"
    MODEL_RUNTIME_FAILURE = "MODEL_RUNTIME_FAILURE"
    EVIDENCE_MERGE_CONFLICT = "EVIDENCE_MERGE_CONFLICT"
    TREE_SCHEMA_FAILURE = "TREE_SCHEMA_FAILURE"
    TREE_EXECUTION_FAILURE = "TREE_EXECUTION_FAILURE"
    COUNTERFACTUAL_CONSTRUCTION_FAILURE = "COUNTERFACTUAL_CONSTRUCTION_FAILURE"
    ANCHOR_MATCHING_FAILURE = "ANCHOR_MATCHING_FAILURE"


def render_value(value: object) -> str:
    """Render values without treating ``False`` or numeric zero as missing."""

    if value is None:
        return "unknown"
    if isinstance(value, bool):
        return "true" if value else "false"
    return str(value)
